# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Dispatch

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMAJS_1_0 = QtWidgets.QMenu(self.menuBar)
        self.menuMAJS_1_0.setObjectName("menuMAJS_1_0")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuRuns = QtWidgets.QMenu(self.menuBar)
        self.menuRuns.setObjectName("menuRuns")
        self.menuGEM = QtWidgets.QMenu(self.menuBar)
        self.menuGEM.setObjectName("menuGEM")
        self.menuRun = QtWidgets.QMenu(self.menuBar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionALife_single = QtWidgets.QAction(MainWindow)
        self.actionALife_single.setObjectName("actionALife_single")
        self.actionALife_runs = QtWidgets.QAction(MainWindow)
        self.actionALife_runs.setObjectName("actionALife_runs")
        self.actionALife_sweep_1 = QtWidgets.QAction(MainWindow)
        self.actionALife_sweep_1.setObjectName("actionALife_sweep_1")
        self.actionALife_sweep_2 = QtWidgets.QAction(MainWindow)
        self.actionALife_sweep_2.setObjectName("actionALife_sweep_2")
        self.actionALife_sweep_3 = QtWidgets.QAction(MainWindow)
        self.actionALife_sweep_3.setObjectName("actionALife_sweep_3")
        self.actionAlife_sweep_4 = QtWidgets.QAction(MainWindow)
        self.actionAlife_sweep_4.setObjectName("actionAlife_sweep_4")
        self.actionALife_sweep_5 = QtWidgets.QAction(MainWindow)
        self.actionALife_sweep_5.setObjectName("actionALife_sweep_5")
        self.actionALife_thermo = QtWidgets.QAction(MainWindow)
        self.actionALife_thermo.setObjectName("actionALife_thermo")
        self.actionGEM_sweep_1 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_1.setObjectName("actionGEM_sweep_1")
        self.actionGEM_sweep_2 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_2.setObjectName("actionGEM_sweep_2")
        self.actionGEM_sweep_3 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_3.setObjectName("actionGEM_sweep_3")
        self.actionGEM_sweep_4 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_4.setObjectName("actionGEM_sweep_4")
        self.actionGEM_sweep_5 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_5.setObjectName("actionGEM_sweep_5")
        self.actionGEM_sweep_6 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_6.setObjectName("actionGEM_sweep_6")
        self.actionRun_once = QtWidgets.QAction(MainWindow)
        self.actionRun_once.setObjectName("actionRun_once")
        self.actionRun_partial = QtWidgets.QAction(MainWindow)
        self.actionRun_partial.setObjectName("actionRun_partial")
        self.actionGEM_sweep_7 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_7.setObjectName("actionGEM_sweep_7")
        self.actionGEM_sweep_8 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_8.setObjectName("actionGEM_sweep_8")
        self.actionGEM_sweep_9 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_9.setObjectName("actionGEM_sweep_9")
        self.actionGEM_sweep_10 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_10.setObjectName("actionGEM_sweep_10")
        self.actionGEM_sweep_11 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_11.setObjectName("actionGEM_sweep_11")
        self.actionGEM_sweep_12 = QtWidgets.QAction(MainWindow)
        self.actionGEM_sweep_12.setObjectName("actionGEM_sweep_12")
        self.actionRun_once_2 = QtWidgets.QAction(MainWindow)
        self.actionRun_once_2.setObjectName("actionRun_once_2")
        self.actionRun_partial_2 = QtWidgets.QAction(MainWindow)
        self.actionRun_partial_2.setObjectName("actionRun_partial_2")
        self.actionRun_WCSS_sims = QtWidgets.QAction(MainWindow)
        self.actionRun_WCSS_sims.setObjectName("actionRun_WCSS_sims")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout_MAJS = QtWidgets.QAction(MainWindow)
        self.actionAbout_MAJS.setObjectName("actionAbout_MAJS")
        self.menuMAJS_1_0.addAction(self.actionAbout_MAJS)
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menuRuns.addAction(self.actionALife_runs)
        self.menuRuns.addAction(self.actionALife_single)
        self.menuRuns.addAction(self.actionALife_thermo)
        self.menuRuns.addSeparator()
        self.menuRuns.addAction(self.actionALife_sweep_1)
        self.menuRuns.addAction(self.actionALife_sweep_2)
        self.menuRuns.addAction(self.actionALife_sweep_3)
        self.menuRuns.addAction(self.actionAlife_sweep_4)
        self.menuRuns.addAction(self.actionALife_sweep_5)
        self.menuRuns.addSeparator()
        self.menuGEM.addAction(self.actionGEM_sweep_7)
        self.menuGEM.addAction(self.actionGEM_sweep_8)
        self.menuGEM.addAction(self.actionGEM_sweep_9)
        self.menuGEM.addAction(self.actionGEM_sweep_10)
        self.menuGEM.addAction(self.actionGEM_sweep_11)
        self.menuGEM.addAction(self.actionGEM_sweep_12)
        self.menuRun.addAction(self.actionRun_once_2)
        self.menuRun.addAction(self.actionRun_partial_2)
        self.menuRun.addAction(self.actionRun_WCSS_sims)
        self.menuBar.addAction(self.menuMAJS_1_0.menuAction())
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuRuns.menuAction())
        self.menuBar.addAction(self.menuGEM.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMAJS_1_0.setTitle(_translate("MainWindow", "MAJS 1.0"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuRuns.setTitle(_translate("MainWindow", "ALife"))
        self.menuGEM.setTitle(_translate("MainWindow", "GEM"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionALife_single.setText(_translate("MainWindow", "ALife single"))
        self.actionALife_runs.setText(_translate("MainWindow", "ALife sims"))
        self.actionALife_sweep_1.setText(_translate("MainWindow", "ALife sweep 1"))
        self.actionALife_sweep_2.setText(_translate("MainWindow", "ALife sweep 2"))
        self.actionALife_sweep_3.setText(_translate("MainWindow", "ALife sweep 3"))
        self.actionAlife_sweep_4.setText(_translate("MainWindow", "ALife sweep 4"))
        self.actionALife_sweep_5.setText(_translate("MainWindow", "ALife sweep 5"))
        self.actionALife_thermo.setText(_translate("MainWindow", "ALife thermo"))
        self.actionGEM_sweep_1.setText(_translate("MainWindow", "GEM sweep 1"))
        self.actionGEM_sweep_2.setText(_translate("MainWindow", "GEM sweep 2"))
        self.actionGEM_sweep_3.setText(_translate("MainWindow", "GEM sweep 3"))
        self.actionGEM_sweep_4.setText(_translate("MainWindow", "GEM sweep 4"))
        self.actionGEM_sweep_5.setText(_translate("MainWindow", "GEM sweep 5"))
        self.actionGEM_sweep_6.setText(_translate("MainWindow", "GEM sweep 6"))
        self.actionRun_once.setText(_translate("MainWindow", "Run once"))
        self.actionRun_partial.setText(_translate("MainWindow", "Run partial"))
        self.actionGEM_sweep_7.setText(_translate("MainWindow", "GEM sweep 1"))
        self.actionGEM_sweep_8.setText(_translate("MainWindow", "GEM sweep 2"))
        self.actionGEM_sweep_9.setText(_translate("MainWindow", "GEM sweep 3"))
        self.actionGEM_sweep_10.setText(_translate("MainWindow", "GEM sweep 4"))
        self.actionGEM_sweep_11.setText(_translate("MainWindow", "GEM sweep 5"))
        self.actionGEM_sweep_12.setText(_translate("MainWindow", "GEM sweep 6"))
        self.actionRun_once_2.setText(_translate("MainWindow", "Run once"))
        self.actionRun_partial_2.setText(_translate("MainWindow", "Run partial"))
        self.actionRun_WCSS_sims.setText(_translate("MainWindow", "Run WCSS sims"))
        self.actionNew.setText(_translate("MainWindow", "New ..."))
        self.actionOpen.setText(_translate("MainWindow", "Open ..."))
        self.actionAbout_MAJS.setText(_translate("MainWindow", "About MAJS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

